name: mass_pro
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# analyzer:
# strong-mode: true
# language:
# enableSuperMixins: true

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  d2_remote:
    path: ./data-run-sdk
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  flutter_treeview: ^1.0.7+1
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flutter_styled_toast: ^2.1.3
  shared_preferences: ^2.0.15
  rxdart: ^0.27.7
  dartx: ^1.1.0
  dartz: ^0.10.1
  dartlin: ^0.6.3
  dio: ^5.0.0
  reflectable: ^4.0.5
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  rounded_loading_button_plus: ^3.0.1
  percent_indicator: ^4.2.3
  scrollable_positioned_list: ^0.3.8
  get: ^4.6.6
  expressions: ^0.2.5+1


dev_dependencies:
#  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  #  sealed_generators: ^1.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/sample/dhis/
    - lib/main/l10n/locales_strings/
    - lib/l10n/
    - assets/images/
    - assets/languages/
# analyzer:
#   strong-mode: true
#   language:
#     enableSuperMixins: true
flutter_intl:
  enabled: true
